server:
  port: 6060

spring:
  application:
    name: CFG-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: ${REPOSITORY_URL}
          username: ${GITHUB_USER}
          password: ${GITHUB_PASSWORD}
          default-label: ${GITHUB_BRANCH}
          clone-on-start: true
          search-paths:
            - '{application}'

# CONFIGURACOES ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'