server:
  port: 6060

spring:
  application:
    name: CFG-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Financas-pessoais/fnp-cfg-config
          search-paths:
            - '{application}'

# CONFIGURACOES ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'